# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 17:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('popeye', '0003_auto_20170919_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='country2',
        ),
    ]
