# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 18:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('popeye', '0004_remove_profile_country2'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentWriting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('keywords', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=1000)),
                ('word_count', models.IntegerField()),
                ('cost', models.CharField(max_length=20)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteBuilding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('navigation_contents', models.CharField(max_length=500)),
                ('cost', models.CharField(max_length=20)),
                ('additional_intructions', models.CharField(max_length=1000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
