# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popeye', '0006_auto_20170923_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.FileField(blank=True, upload_to='profile_picture'),
        ),
    ]
