# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 19:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('popeye', '0008_auto_20170928_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
    ]
