# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popeye', '0009_remove_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentwriting',
            name='topic',
            field=models.CharField(choices=[('fr', 'Entertainment'), ('sr', 'Education')], max_length=255),
        ),
    ]
