# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popeye', '0010_auto_20171001_2244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contentwriting',
            old_name='cost',
            new_name='article_cost',
        ),
        migrations.RenameField(
            model_name='websitebuilding',
            old_name='cost',
            new_name='website_cost',
        ),
        migrations.AlterField(
            model_name='contentwriting',
            name='topic',
            field=models.CharField(max_length=255),
        ),
    ]
