# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-20 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popeye', '0012_auto_20171018_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentwriting',
            name='is_done',
            field=models.IntegerField(default=0),
        ),
    ]
